### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by lemur4ek** [lemur4ek/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Koala4ka** [comment]
https://www.linkedin.com/in/аnna-hovorkova-550a99158/
https://github.com/Koala4ka
https://www.instagram.com/koala4ka/
+38(096)859-77-96
gvani@ukr.net
